# Generated by Django 5.1.2 on 2024-10-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '用户', 'verbose_name_plural': 'verbose_name'},
        ),
    ]
