# Generated by Django 5.1.2 on 2024-10-21 09:38

import basic_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ztrybh', models.CharField(max_length=50, verbose_name='在逃人员编号')),
                ('swzp', models.ImageField(blank=True, max_length=255, null=True, upload_to=basic_info.models.swzp_image_upload_path, verbose_name='上网图片')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号码')),
                ('hjdz', models.CharField(blank=True, max_length=100, null=True, verbose_name='户籍地址')),
                ('ajlb', models.CharField(blank=True, max_length=50, null=True, verbose_name='案件类别')),
                ('swdw', models.CharField(blank=True, max_length=50, null=True, verbose_name='上网单位')),
                ('swsj', models.DateField(blank=True, null=True, verbose_name='上网日期')),
                ('zt', models.CharField(choices=[('1', '在逃'), ('2', '撤销'), ('3', '已抓获未撤销')], max_length=50, verbose_name='状态')),
                ('zhdw', models.CharField(blank=True, max_length=50, null=True, verbose_name='抓获单位')),
                ('zhsj', models.DateField(blank=True, null=True, verbose_name='抓获日期')),
                ('jtbd', models.CharField(blank=True, default='查看', max_length=50, verbose_name='静态比对')),
                ('dtbd', models.CharField(blank=True, default='查看', max_length=50, verbose_name='动态比对')),
                ('yp', models.CharField(default='查看', max_length=50, verbose_name='研判')),
                ('bssw', models.TextField(blank=True, choices=[('1', '是'), ('2', '否')], max_length=50, null=True, verbose_name='备注')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '在逃人员信息',
                'verbose_name_plural': '在逃人员信息',
            },
        ),
        migrations.CreateModel(
            name='DtImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ztrybh', models.CharField(max_length=50, verbose_name='在逃人员编号')),
                ('dtbd', models.ImageField(blank=True, max_length=255, null=True, upload_to=basic_info.models.dtbd_image_upload_path, verbose_name='动态比对图片')),
                ('cz', models.CharField(blank=True, choices=[('1', '排除'), ('2', '已抓获'), ('3', '确认')], max_length=50, null=True, verbose_name='处置')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '动态比对图片',
                'verbose_name_plural': '动态比对图片',
            },
        ),
        migrations.CreateModel(
            name='Gz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ztrybh', models.CharField(max_length=50, verbose_name='在逃人员编号')),
                ('gzr', models.CharField(blank=True, max_length=50, null=True, verbose_name='关注人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='JtImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ztrybh', models.CharField(max_length=50, verbose_name='在逃人员编号')),
                ('jtbd', models.ImageField(blank=True, max_length=255, null=True, upload_to=basic_info.models.jtbd_image_upload_path, verbose_name='静态比对图片')),
                ('cz', models.CharField(blank=True, choices=[('1', '排除'), ('2', '已抓获'), ('3', '确认')], max_length=50, null=True, verbose_name='处置')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '静态比对图片',
                'verbose_name_plural': '静态比对图片',
            },
        ),
        migrations.CreateModel(
            name='Sfyj',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ztrybh', models.CharField(max_length=50, verbose_name='在逃人员编号')),
                ('swsj', models.DateField(blank=True, null=True, verbose_name='上网日期')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号码')),
                ('hdsj', models.DateTimeField(blank=True, null=True, verbose_name='活动时间')),
                ('sjly', models.CharField(blank=True, max_length=50, null=True, verbose_name='数据来源')),
                ('yjxx', models.CharField(blank=True, max_length=100, null=True, verbose_name='预警信息')),
                ('cz', models.CharField(blank=True, max_length=50, null=True, verbose_name='处置')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '身份信息预警',
                'verbose_name_plural': '身份信息预警',
            },
        ),
        migrations.CreateModel(
            name='SwImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ztrybh', models.CharField(max_length=50, verbose_name='在逃人员编号')),
                ('swzp', models.ImageField(blank=True, max_length=255, null=True, upload_to=basic_info.models.swzp_image_upload_path, verbose_name='上网图片')),
                ('cz', models.CharField(choices=[('1', '本人'), ('2', '非本人')], default='1', max_length=50, verbose_name='处置')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '上网图片',
                'verbose_name_plural': '上网图片',
            },
        ),
        migrations.CreateModel(
            name='Ypbg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ztrybh', models.CharField(max_length=50, verbose_name='在逃人员编号')),
                ('swsj', models.DateField(blank=True, null=True, verbose_name='上网日期')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号码')),
                ('swdw', models.CharField(blank=True, max_length=50, null=True, verbose_name='上网单位')),
                ('sbdw', models.CharField(blank=True, max_length=50, null=True, verbose_name='上报单位')),
                ('sbsj', models.DateTimeField(blank=True, null=True, verbose_name='上报时间')),
                ('dqsj', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('bdwsbsj', models.DateTimeField(blank=True, null=True, verbose_name='本单位上报时间')),
                ('bdwdqsj', models.DateTimeField(blank=True, null=True, verbose_name='本单位上报到期时间')),
                ('fz', models.CharField(blank=True, max_length=50, null=True, verbose_name='分值')),
                ('zg', models.CharField(blank=True, max_length=50, null=True, verbose_name='战果认定')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '研判报告',
                'verbose_name_plural': '研判报告',
            },
        ),
        migrations.CreateModel(
            name='Ypjl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ztrybh', models.CharField(max_length=50, verbose_name='在逃人员编号')),
                ('ypnr', models.TextField(blank=True, null=True, verbose_name='研判记录')),
                ('ypr', models.CharField(max_length=50, verbose_name='研判人')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '研判记录',
                'verbose_name_plural': '研判记录',
            },
        ),
        migrations.CreateModel(
            name='Zhzg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ztrybh', models.CharField(max_length=50, verbose_name='在逃人员编号')),
                ('swsj', models.DateField(blank=True, null=True, verbose_name='上网日期')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号码')),
                ('swdw', models.CharField(blank=True, max_length=50, null=True, verbose_name='上网单位')),
                ('fz', models.CharField(blank=True, max_length=50, null=True, verbose_name='分值')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '抓获战果',
                'verbose_name_plural': '抓获战果',
            },
        ),
    ]
