# Generated by Django 5.1.2 on 2024-10-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gz',
            options={'verbose_name': '关注', 'verbose_name_plural': '关注'},
        ),
    ]
