# Generated by Django 5.1.2 on 2024-10-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0002_alter_gz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='bssw',
            field=models.TextField(blank=True, choices=[('1', '是'), ('2', '否')], max_length=50, null=True, verbose_name='本市上网'),
        ),
    ]
