# Generated by Django 5.1.2 on 2024-10-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0003_alter_basicinfo_bssw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='swzp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上网图片'),
        ),
        migrations.AlterField(
            model_name='dtimage',
            name='cz',
            field=models.CharField(blank=True, choices=[('1', '排除'), ('2', '已抓获'), ('3', '确认')], default='3', max_length=50, verbose_name='处置'),
        ),
        migrations.AlterField(
            model_name='jtimage',
            name='cz',
            field=models.CharField(blank=True, choices=[('1', '排除'), ('2', '已抓获'), ('3', '确认')], default='3', max_length=50, verbose_name='处置'),
        ),
    ]
