# Generated by Django 5.1.2 on 2024-10-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0004_alter_basicinfo_swzp_alter_dtimage_cz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfyj',
            name='hdsj',
            field=models.DateField(blank=True, null=True, verbose_name='活动时间'),
        ),
    ]
