# Generated by Django 5.1.2 on 2024-10-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0007_gxr'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='gxr',
            field=models.CharField(default='查看', max_length=50, verbose_name='关系人'),
        ),
    ]
