# Generated by Django 5.1.2 on 2024-10-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0008_basicinfo_gxr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gxr',
            name='gxr_id',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='关系人身份证号码'),
        ),
    ]
