# Generated by Django 5.1.2 on 2024-10-22 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0012_alter_gxr_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gxr',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='ypbg',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ypbg_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
    ]
