# Generated by Django 5.1.2 on 2024-10-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0013_alter_gxr_updated_by_alter_ypbg_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ypbg',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人'),
        ),
    ]
