# Generated by Django 5.1.2 on 2024-10-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0014_alter_ypbg_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ypbg',
            name='zgdw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='战果单位'),
        ),
        migrations.AddField(
            model_name='zhzg',
            name='zgdw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='战果单位'),
        ),
    ]
