# Generated by Django 5.1.2 on 2024-10-29 03:57

import basic_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0015_ypbg_zgdw_zhzg_zgdw'),
    ]

    operations = [
        migrations.AddField(
            model_name='ypjl',
            name='yptp',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=basic_info.models.yp_image_upload_path, verbose_name='研判记录图片'),
        ),
    ]
