# Generated by Django 5.1.2 on 2024-10-29 10:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0016_ypjl_yptp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ypjl',
            name='ypnr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='研判记录'),
        ),
    ]
