# Generated by Django 5.1.2 on 2024-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0017_alter_ypjl_ypnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ypjl',
            name='ypnr',
            field=models.TextField(blank=True, null=True, verbose_name='研判记录'),
        ),
    ]
