# Generated by Django 5.1.2 on 2024-10-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0018_alter_ypjl_ypnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ypjl',
            name='xq',
            field=models.CharField(default='查看', max_length=50, verbose_name='详情'),
        ),
    ]
