# Generated by Django 5.1.2 on 2024-10-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0019_ypjl_xq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='gxr',
        ),
    ]
