# Generated by Django 5.1.2 on 2024-10-29 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0021_remove_basicinfo_dtbd_remove_basicinfo_jtbd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ypjl',
            name='xq',
        ),
    ]
