# Generated by Django 5.1.2 on 2024-11-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0023_alter_basicinfo_bssw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='bssw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='本市上网'),
        ),
    ]
