# Generated by Django 5.1.2 on 2024-11-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0024_alter_basicinfo_bssw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='swzp',
        ),
    ]
