# Generated by Django 5.1.2 on 2024-11-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0025_remove_basicinfo_swzp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='id_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号码'),
        ),
    ]
