# Generated by Django 5.1.2 on 2024-11-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0026_alter_basicinfo_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='id_card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='gxr',
            name='id_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='sfyj',
            name='id_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='ypbg',
            name='id_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号码'),
        ),
        migrations.AlterField(
            model_name='zhzg',
            name='id_card',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号码'),
        ),
    ]
