# Generated by Django 5.1.2 on 2024-11-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0028_alter_basicinfo_zt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='zt',
            field=models.CharField(blank=True, choices=[('1', '在逃'), ('2', '撤销'), ('3', '已抓获未撤销')], default='1', max_length=50, null=True, verbose_name='状态'),
        ),
    ]
