# Generated by Django 5.1.2 on 2024-11-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0029_alter_basicinfo_zt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='zt',
            field=models.CharField(blank=True, choices=[('在逃', '在逃'), ('撤销', '撤销'), ('已抓获未撤销', '已抓获未撤销')], default='在逃', max_length=50, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='dtimage',
            name='cz',
            field=models.CharField(blank=True, choices=[('排除', '排除'), ('已抓获', '已抓获'), ('确认', '确认')], default='确认', max_length=50, verbose_name='处置'),
        ),
        migrations.AlterField(
            model_name='jtimage',
            name='cz',
            field=models.CharField(blank=True, choices=[('排除', '排除'), ('已抓获', '已抓获'), ('确认', '确认')], default='确认', max_length=50, verbose_name='处置'),
        ),
        migrations.AlterField(
            model_name='swimage',
            name='cz',
            field=models.CharField(choices=[('本人', '本人'), ('非本人', '非本人')], default='本人', max_length=50, verbose_name='处置'),
        ),
    ]
