# Generated by Django 5.1.2 on 2024-11-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0031_remove_gxr_tfgx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号'),
        ),
        migrations.AlterField(
            model_name='dtimage',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号'),
        ),
        migrations.AlterField(
            model_name='gxr',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号'),
        ),
        migrations.AlterField(
            model_name='gz',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号'),
        ),
        migrations.AlterField(
            model_name='jtimage',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号'),
        ),
        migrations.AlterField(
            model_name='sfyj',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号'),
        ),
        migrations.AlterField(
            model_name='swimage',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号'),
        ),
        migrations.AlterField(
            model_name='ypbg',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号'),
        ),
        migrations.AlterField(
            model_name='ypjl',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号'),
        ),
        migrations.AlterField(
            model_name='zhzg',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号'),
        ),
        migrations.AddIndex(
            model_name='basicinfo',
            index=models.Index(fields=['ztrybh'], name='basic_info__ztrybh_7ed61e_idx'),
        ),
        migrations.AddIndex(
            model_name='dtimage',
            index=models.Index(fields=['ztrybh'], name='basic_info__ztrybh_85141d_idx'),
        ),
        migrations.AddIndex(
            model_name='gxr',
            index=models.Index(fields=['ztrybh'], name='basic_info__ztrybh_f9e1de_idx'),
        ),
        migrations.AddIndex(
            model_name='gz',
            index=models.Index(fields=['ztrybh'], name='basic_info__ztrybh_7f2ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='jtimage',
            index=models.Index(fields=['ztrybh'], name='basic_info__ztrybh_63e5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='sfyj',
            index=models.Index(fields=['ztrybh'], name='basic_info__ztrybh_ee7c79_idx'),
        ),
        migrations.AddIndex(
            model_name='swimage',
            index=models.Index(fields=['ztrybh'], name='basic_info__ztrybh_aedf14_idx'),
        ),
        migrations.AddIndex(
            model_name='ypbg',
            index=models.Index(fields=['ztrybh'], name='basic_info__ztrybh_c3a293_idx'),
        ),
        migrations.AddIndex(
            model_name='ypjl',
            index=models.Index(fields=['ztrybh'], name='basic_info__ztrybh_0ea624_idx'),
        ),
        migrations.AddIndex(
            model_name='zhzg',
            index=models.Index(fields=['ztrybh'], name='basic_info__ztrybh_1d3abe_idx'),
        ),
    ]
