# Generated by Django 5.1.2 on 2024-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0033_alter_basicinfo_swsj'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='xxzjbh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='信息主键编号'),
        ),
    ]
