# Generated by Django 5.1.2 on 2024-11-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0035_alter_gz_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='ztrybh',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='在逃人员编号'),
        ),
    ]
