# Generated by Django 5.1.2 on 2024-11-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0036_alter_basicinfo_ztrybh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='swsj',
            field=models.DateField(blank=True, null=True, verbose_name='上网时间'),
        ),
    ]
