# Generated by Django 5.1.2 on 2024-11-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0037_alter_basicinfo_swsj'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='jyaq',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='简要案情'),
        ),
    ]
