# Generated by Django 5.1.2 on 2024-11-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0040_alter_basicinfo_ztrybh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ztrybh', models.CharField(db_index=True, max_length=50, verbose_name='在逃人员编号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号码')),
                ('ajlb', models.CharField(blank=True, max_length=50, null=True, verbose_name='案件类别')),
                ('swdw', models.CharField(blank=True, max_length=50, null=True, verbose_name='上网单位')),
                ('swsj', models.DateTimeField(blank=True, null=True, verbose_name='上网时间')),
                ('zhdw', models.CharField(blank=True, max_length=50, null=True, verbose_name='抓获单位')),
                ('zhsj', models.DateField(blank=True, null=True, verbose_name='抓获日期')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '在逃人员信息',
                'verbose_name_plural': '在逃人员信息',
            },
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='zt',
            field=models.CharField(blank=True, choices=[('在逃', '在逃'), ('已抓获', '已抓获')], default='在逃', max_length=50, null=True, verbose_name='状态'),
        ),
    ]
