# Generated by Django 5.1.2 on 2024-11-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0041_backout_alter_basicinfo_zt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='zhdw',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='zhsj',
        ),
    ]
