# Generated by Django 5.1.2 on 2024-11-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0042_remove_basicinfo_zhdw_remove_basicinfo_zhsj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backout',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='backout',
            name='updated_by',
        ),
    ]
