# Generated by Django 5.1.2 on 2024-11-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0043_remove_backout_update_at_remove_backout_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfyj',
            name='yjxx',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='预警信息'),
        ),
    ]
