# Generated by Django 5.1.2 on 2024-11-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0044_alter_sfyj_yjxx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backout',
            old_name='zhsj',
            new_name='cxsj',
        ),
    ]
