# Generated by Django 5.1.2 on 2024-11-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0045_rename_zhsj_backout_cxsj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backout',
            name='cxsj',
            field=models.DateTimeField(blank=True, null=True, verbose_name='抓获日期'),
        ),
    ]
