# Generated by Django 5.1.2 on 2024-11-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0046_alter_backout_cxsj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ypbg',
            name='bdwdqsj',
        ),
        migrations.RemoveField(
            model_name='ypbg',
            name='bdwsbsj',
        ),
        migrations.RemoveField(
            model_name='ypbg',
            name='zgdw',
        ),
        migrations.AddField(
            model_name='ypbg',
            name='zhdw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='抓获单位'),
        ),
        migrations.AddField(
            model_name='ypbg',
            name='zhsj',
            field=models.DateTimeField(blank=True, null=True, verbose_name='抓获时间'),
        ),
    ]
