# Generated by Django 5.1.2 on 2024-11-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0047_remove_ypbg_bdwdqsj_remove_ypbg_bdwsbsj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ypbg',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='ypbg',
            name='updated_by',
        ),
    ]
