# Generated by Django 5.1.2 on 2024-11-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0048_remove_ypbg_update_at_remove_ypbg_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ypbg',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='ypbg',
            name='updated_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='更新人'),
        ),
    ]
