# Generated by Django 5.1.2 on 2024-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0049_ypbg_update_at_ypbg_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ypbg',
            name='xsfw',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='线索范围'),
        ),
    ]
