# Generated by Django 5.1.2 on 2024-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0050_ypbg_xsfw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ypbg',
            name='swsj',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上网时间'),
        ),
    ]
