# Generated by Django 5.1.2 on 2024-11-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0054_ypbg_cxsj_alter_backout_cxsj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zhzg',
            old_name='zgdw',
            new_name='zhdw',
        ),
    ]
