# Generated by Django 5.1.2 on 2024-11-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0056_alter_zhzg_zhdw'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhzg',
            name='zhsj',
            field=models.DateTimeField(blank=True, null=True, verbose_name='抓获时间'),
        ),
    ]
