# Generated by Django 5.1.2 on 2024-11-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0057_zhzg_zhsj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zhzg',
            old_name='zhsj',
            new_name='cxsj',
        ),
    ]
